(function(){
	jQuery(document).ready(function(){
		var now = new Date();
		var start = new Date(now.getFullYear(), 0, 0);
		var diff = now - start;
		var oneDay = 1000 * 60 * 60 * 24;
		var day = Math.floor(diff / oneDay); // aroja el dia del año en el que estamos

		//Todos los santos por dia, en el 0 no hay nadie
		var dias = [
			"Nadie",
			"María",
			"Gregorio",
			"Genoveva",
			"Rigoberto",
			"Emilia",
			"Wilma",
			"Raimundo",
			"Luciano",
			"Lucrecia",
			"Gonzalo",
			"Alejandro",
			"Julián",
			"Hilario",
			"Félix",
			"Raquel",
			"Marcelo",
			"Antonio",
			"Priscila",
			"Mario",
			"Sebastián",
			"Inés",
			"Vicente",
			"Virginia",
			"Francisco",
			"Elvira",
			"Paula",
			"Ángela",
			"Tomás",
			"Valerio ",
			"Martina",
			"Marcela",
			"Severiano ",
			"El Señor",
			"Oscar ",
			"Gilberto",
			"Agueda",
			"Doris",
			"Gastón",
			"Jacqueline",
			"Rebeca",
			"Escolástica",
			"Lourdes",
			"Pamela",
			"Batriz",
			"Valentino ",
			"Jovita",
			"Samuel",
			"Alexis",
			"Bernardita",
			"Álvaro ",
			"Claudio ",
			"Severino ",
			"Eleonora",
			"Florencio ",
			"Rubén",
			"Néstor ",
			"Augusto ",
			"Leandro",
			"Román",
			"Dositeo",
			"Rosendo",
			"Lucio",
			"Celedonio",
			"Ariel",
			"Olivia",
			"Elcira",
			"Perpétua",
			"Juan de Dios",
			"Francisca",
			"Macario",
			"Eulogio",
			"Norma",
			"Rodrigo",
			"Matilde",
			"Luisa",
			"Heriberto ",
			"Patricio ",
			"Cirilo ",
			"José ",
			"Alejandra ",
			"Eugenia ",
			"Lea ",
			"Dimas ",
			"Elba",
			"Anunciación ",
			"Braulio ",
			"Ruperto ",
			"Octavio ",
			"Gladys ",
			"Artemio ",
			"Benjamín",
			"Hugo ",
			"Sandra",
			"Ricardo",
			"Isidoro ",
			"Vicente",
			"Edith ",
			"Juan Bautista",
			"Constanza",
			"Demetrio",
			"Ezequiel ",
			"Estanislao ",
			"Arnoldo",
			"Martín",
			"Máximo ",
			"Crescente",
			"Flavio ",
			"Leopoldo ",
			"Wladimir ",
			"Ema ",
			"Edgardo ",
			"Anselmo ",
			"Karina ",
			"Jorge ",
			"Fidel ",
			"Marcos ",
			"Marcelino ",
			"Zita ",
			"Valeria ",
			"Catalina ",
			"Amador",
			"José Obrero ",
			"Boris",
			"Santa Cruz",
			"Felipe",
			"Judit",
			"Eleodoro",
			"Domitila",
			"Segundo",
			"Isaías",
			"Antonino-a,",
			"Estela",
			"Pancracio",
			"NS Fátima",
			"Matías",
			"Isidro",
			"Honorato ",
			"Pascual ",
			"Erica ",
			"Yvo-ne ",
			"Bernardino ",
			"Constantino ",
			"Rita ",
			"Desiderio ",
			"Susana ",
			"Ma.Magdalena",
			"Mariana ",
			"Emilio",
			"Germán ",
			"Maximiano ",
			"Fernando ",
			"Visitación",
			"Juvenal ",
			"Marcelino",
			"Maximiliano",
			"Frida ",
			"Bonifacio ",
			"Norberto",
			"Claudio ",
			"Armando ",
			"Efr&eacuten ",
			"Paulina ",
			"Bernabé ",
			"Onofre ",
			"Antonio",
			"Eliseo ",
			"Leonidas",
			"Aurelio ",
			"Ismael ",
			"Salom&oacuten ",
			"Romualdo ",
			"Florentino ",
			"Raul ",
			"Paulino ",
			"Marcial ",
			"Juan Bautista ",
			"Guillermo ",
			"Pelayo ",
			"Cirilo ",
			"Ireneo ",
			"Pedro y Pablo",
			"Adolfo",
			"Ester ",
			"Gloria",
			"Tomás",
			"Isabel ",
			"Antonio-María ",
			"María Goretti",
			"Fermín",
			"Eugenio",
			"Verónica ",
			"Elías",
			"Benito ",
			"Filomena",
			"Enrique",
			"Camilo ",
			"Buenaventura",
			"Carmen ",
			"Carolina ",
			"Federico ",
			"Arsenio ",
			"Marina ",
			"Daniel ",
			"Ma. Magdalena",
			"Brigida ",
			"Cristina ",
			"Santiago ",
			"Joaquín ",
			"Natalia ",
			"Celso ",
			"Marta ",
			"Abdón ",
			"Ignacio",
			"Alfonso",
			"Eusebio",
			"Lydia",
			"Juan María",
			"Osvaldo",
			"Transfiguración",
			"Sixto",
			"Domingo",
			"Justo",
			"Lorenzo",
			"Clara de Asís",
			"Laura",
			"Víctor",
			"Maximiliano",
			"Asunción ",
			"Esteba ",
			"Jacinto ",
			"Alberto Hurtado",
			"Mariano ",
			"Bernardo ",
			"Graciela ",
			"María Reina ",
			"Donato ",
			"Bartolomé ",
			"Luís",
			"César ",
			"Mónica ",
			"Agustín ",
			"Juan Bautista ",
			"Rosa de Lima ",
			"Ramón",
			"Arturo ",
			"Moisés ",
			"Gregorio ",
			"Irma ",
			"Victorino ",
			"Evelyne ",
			"Regina ",
			"Natividad ",
			"Sergio ",
			"Adalberto ",
			"Orlando",
			"María",
			"Crisóstomo",
			"Imelda",
			"Dolores",
			"Cornelio ",
			"Roberto ",
			"José ",
			"Jenaro ",
			"Amelia",
			"Mateo ",
			"Mauricio ",
			"Lino ",
			"Carmen ",
			"Aurelio ",
			"Cosme ",
			"Vicente ",
			"Wenceslao ",
			"Miguel ",
			"Jerónimo",
			"Teresita",
			"Angeles ",
			"Gerardo",
			"Francisco",
			"Flor ",
			"Bruno ",
			"Rosario",
			"Begoña",
			"Dionisio",
			"Francisco",
			"Soledad ",
			"Pilar",
			"Eduardo ",
			"Calixto ",
			"Teresa ",
			"Eduvigis",
			"Ignacio ",
			"Lucas ",
			"Pablo ",
			"Irene ",
			"Úrsula ",
			"Sara ",
			"Remigio ",
			"Antonio ",
			"Olga ",
			"Darío ",
			"Gustavo ",
			"Judas ",
			"Narciso ",
			"Alonso ",
			"Quintin",
			"¡Todos! ",
			"Fieles",
			"Martín ",
			"Carlos ",
			"Silvia ",
			"Leonardo",
			"Ernesto-ina",
			"Ninfa ",
			"Teodoro ",
			"León ",
			"Martín",
			"Cristián",
			"Diego ",
			"Humberto ",
			"Alberto ",
			"Margarita ",
			"Isabel ",
			"Elsa ",
			"Andrés ",
			"Edmundo ",
			"La Virgen ",
			"Cecilia ",
			"Clemento ",
			"Flora ",
			"Catalina ",
			"Delfina ",
			"Virgilio ",
			"Blanca ",
			"Saturnino ",
			"Andrés",
			"Florencia ",
			"Viviana ",
			"Fco Javier",
			"Bárbara ",
			"Ada ",
			"Nicolás ",
			"Ambrosio ",
			"Inmaculada C. ",
			"Jéssica ",
			"Eulalia ",
			"Dámaso ",
			"NS de Guadalupe ",
			"Lucía ",
			"Juan de la Cruz ",
			"Reinaldo ",
			"Alicia ",
			"Lázaro ",
			"Sonia ",
			"Urbano ",
			"Abrahám ",
			"Pedro ",
			"Fabiola ",
			"Victoria ",
			"Adela ",
			"Noel ",
			"Esteban ",
			"Juan ",
			"Inocentes ",
			"David ",
			"Rogelio ",
			"Silvestre"
		];

		//Capura el año actual
		var d = new Date();
		var ano = d.getFullYear();
		var mostrar = document.getElementById("mostrar");

		//Pregunta si el año es bisiesto
		if(mostrar){
			 if ((((ano%100)!=0)&&((ano%4)==0))||((ano%400)==0)){
			 	mostrar.innerHTML=dias[day];
			 } else {
			 	dias.splice(59,1);
			 	mostrar.innerHTML=dias[day];
			 }
		}
});
})();
 
